version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PrimeiraFuncaoSAMStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tfnsl4rvzmmo"
s3_prefix = "PrimeiraFuncaoSAMStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
